steps:
  - name: 'docker/compose:v2.20.2-desktop.1' 
    entrypoint: '/bin/sh' 
    args:
      - '-c'
      - |
        docker-compose build \
          --build-arg PROJECT_ID=$PROJECT_ID \
          --build-arg SHORT_SHA=$SHORT_SHA \
          --build-arg POSTGRES_USER=myuser \
          --build-arg POSTGRES_PASSWORD=qwezxc \
          --build-arg POSTGRES_DB=restaurant

  # Tag the built images with the desired tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_app:latest', 'europe-west1-docker.pkg.dev/$PROJECT_ID/restaurantordertaker/app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_front:latest', 'europe-west1-docker.pkg.dev/$PROJECT_ID/restaurantordertaker/front:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_db:latest', 'europe-west1-docker.pkg.dev/$PROJECT_ID/restaurantordertaker/postgres:$SHORT_SHA']

  # Push the tagged images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/restaurantordertaker/app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/restaurantordertaker/front:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/restaurantordertaker/postgres:$SHORT_SHA']
