version: '3'

services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: qwezxc
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"

  app:
    build:
      context: ./Back-end
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=myuser
      - DB_PASSWORD=qwezxc
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=restaurant
    volumes:
      - ./Back-end:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - deploy_network

  front:
    build:
      context: ./Front-end
    ports:
      - "8080:8080"
      # - "8501:8501"
    depends_on:
      - app
    networks:
      - deploy_network

  networks:
    deploy_network:
      driver: bridge

    
